### ISSUE TITLE
Order grids by feature weight

### ISSUE THREAD

**Issue by corysimmons** [corysimmons/compare.gs#2]
Stop making bad grids more popular. Bootstrap should go towards the bottom of the list whereas Susy should go towards the top.

**Comment by corysimmons** [comment]
Ideally these could be ranked as well. A grid being responsive is more important than a grid being available in LESS.

Rank value could be debated/agreed upon in Issues.

**Comment by peterramsing** [comment]
I think rank may be too subjective and determined by what a project needs this might be a bit controversial.

That being said, I think it might be good to define what this project is trying to do. If it is ranking grids based on features then my comment is `null`. However, I imagine this as more of a tool to see what grid might be best for a project.

For example: [Skeleton](http://getskeleton.com/) doesn't have many features but would "rank" a lot higher than [Bootstrap](http://getbootstrap.com/) if all one needed was something for a [proof of concept](http://peter.coffee/codechallenge/) because of the fact it has less features. However, Bootstrap would "beat out" Skeleton if you needed more features.

What **I do think would be cool** is to have a selector for the type of project and recommend grids based on that. Maybe something that asks "what's your preferred pre-processor?" "do you want the grid in HTML or in your CSS?" etc... then "ranking" the grids based on those answers.

**Comment by corysimmons** [comment]
I think this is a different project, but I think your idea sounds cool too.

Maybe in the future we can create such a project, but for now I like the idea of providing a table of grids and their features. And rather than ordering the grids by which one was added to the array of grids first or last, I think it'd be better to order them by number of features.

Number of features could be subjective though. I might have 50 small features, but my grid might not be responsive. Should my grid be ordered higher than any responsive grid? Should people see that first?

If a grid hasn't been maintained in years, should it outrank a similar grid that is maintained? Should people see the popular/unmaintained project before the less popular/maintained project?

This tool is basically designed to help users quickly determine what the good grids ("good" being determined by feature rank; feature rank being determined by open Issue discussion/debate) are instead of having to manually try out 50 grids.

To that end, I expect this tool to up the game of grids.
